#167728011 Setting up coveralls
andela/cyclops-backend pull request #15
Opened 2019-08-16 21:33 UTC by Wokoro

**What does this PR do?**
  
Implementation to allow code test coverage report for the project using coveralls.

  **Description of Task to be completed?**
  * Added repository to coveralls online service so that repository can be tracked.
  * Added script to send the test reports generated locally or through a continuous integration platform e.g TravisCI to coveralls online service.
  * Added test coverage badge to `README.md`
  * Created coverall.yml file, to hold configuration data for coveralls service.

  **How should this be manually tested?**

  #### step 1
  clone repository
  `git clone git@github.com:andela/cyclops-backend.git`

  #### step 2
  Install npm packages.
  Navigate to root project directory and run `npm install`

  #### step 3
  Write unit tests for a given feature

  #### step 4
  Generate test reports

  #### step 5 
  Send reports generated to coveralls online service.
  Navigate to project root directory and run `npm run coveralls`

  #### step 6
  Refresh `README.md` and observe coverage result updated in badge.

  **Any background context you want to provide?**

  * npm packages most be install
  * test data must be generated.
  * Test report must be sent to coverall online service

  **What are the relevant stories?**
  [#167728011](https://www.pivotaltracker.com/story/show/167728011)

  **Screenshots (if appropriate)**

  none

  **Questions:**

  none

2019-08-16 21:39 UTC, richienabuk approved these changes

2019-08-17 06:06 UTC, Kingobaino approved these changes

2019-08-19 05:42 UTC, justinefe approved these changes

2019-08-19 16:01 UTC, chukwuemekachm reviewed
Looks good @Wokoro.
I have a question below. 👇🏽

2019-08-19 16:01 UTC, chukwuemekachm commented on package.json
> +    "db:connect": "babel-node ./src/database/config",
Why the `db:connent` script? @Wokoro.
What do we want to achieve with it?

2019-08-19 16:25 UTC, Wokoro commented on package.json
> +    "db:connect": "babel-node ./src/database/config",
It's redundant, it was used for testing my setup I would remove it ASAP.

Thanks for pointing it out.

2019-08-19 20:45 UTC, chukwuemekachm requested changes
Hey @Wokoro.
Your PR just removed the Travis badge on our README. The `Coveralls` badge also doesn't display coverage.

2019-08-19 20:45 UTC, chukwuemekachm commented on README.md
> +[![Reviewed by Hound](https://img.shields.io/badge/Reviewed_by-Hound-8E64B0.svg)](https://houndci.com) [![Coverage Status](https://coveralls.io/repos/github/andela/cyclops-backend/badge.svg?branch=de
Can you return the `Travis` badge here?

2019-08-19 21:31 UTC, Wokoro commented on README.md
> +[![Reviewed by Hound](https://img.shields.io/badge/Reviewed_by-Hound-8E64B0.svg)](https://houndci.com) [![Coverage Status](https://coveralls.io/repos/github/andela/cyclops-backend/badge.svg?branch=de
Sorry about the removal of the badge I would fix th.

As for reporting, travis.yml I would have to edit Travis.yml file to send coverage reports to coveralls...

So I think the *writing unit test* should be merged into `develop` branch so there would be tests to report....

What do you think @chukwuemekachm

2019-08-20 10:20 UTC, chukwuemekachm commented on README.md
> +[![Reviewed by Hound](https://img.shields.io/badge/Reviewed_by-Hound-8E64B0.svg)](https://houndci.com) [![Coverage Status](https://coveralls.io/repos/github/andela/cyclops-backend/badge.svg?branch=de
I'll merge this now and @Abobos will resolve report the coverage results to coveralls.

2019-08-20 10:20 UTC, chukwuemekachm approved these changes
LGTM

2019-08-20 10:20 UTC, merged