#167728008 Setup unit tests
andela/cyclops-backend pull request #20
Opened 2019-08-19 18:25 UTC by Abobos

**What does this PR do?**

 Setup Unit Tests

**Description of Task to be completed?**

- Install mocha, chai, and chai-http dependency
- Write unit test to GET route to "/"
- Write a script in package.json to run test

**How should this be manually tested?**

- Open terminal
- Clone this repo
- run ``npm install``
- run ``npm test``

**Any background context you want to provide?**

 (Chai assertion library)[https://www.chaijs.com/api/bdd/]

  **What are the relevant stories?**

  (#167728008)[https://www.pivotaltracker.com/story/show/167728008]

**Screenshots (if appropriate)**
![server test js - cyclops-backend - Visual Studio Code 8_19_2019 7_14_49 PM](https://user-images.githubusercontent.com/39123908/63289474-1f36ce80-c2b7-11e9-9ed2-1867ad6bb56d.png)

**Questions:**

None

2019-08-19 19:59 UTC, Wokoro commented on package.json
> +    "mocha": "^6.2.0",
Well done bro.
I think we would need `sinon` packages too, so we can stub external parts of our unit test.

2019-08-19 20:04 UTC, dieudonneAwa approved these changes

2019-08-19 20:06 UTC, Wokoro reviewed
I think we need a package that would enable us `stub` external parts of our unit tests.

2019-08-19 20:06 UTC, Wokoro commented on package.json
> +    "mocha": "^6.2.0",
Well done bro.
I think we would need `sinon` packages too, so we can stub external parts of our unit test.

2019-08-19 21:20 UTC, Abobos commented on package.json
> +    "mocha": "^6.2.0",
What is Sinon packages?

2019-08-19 22:27 UTC, Wokoro commented on package.json
> +    "mocha": "^6.2.0",
It's a package that allow us to do things like, stubing, spying and mocking when writing unit tests...

2019-08-20 06:28 UTC, Abobos commented on package.json
> +    "mocha": "^6.2.0",
okay...... I will learn about it .... But I what I did would still suffice.. right?

2019-08-20 07:37 UTC, richienabuk approved these changes

2019-08-20 14:35 UTC, chukwuemekachm requested changes
Looking good @Abobos.
Have a single concern though.

2019-08-20 14:35 UTC, chukwuemekachm commented on .coveralls.yml
> +repo_token: oXbUEfKxrsWp5IKNRE13j9RMBpGnTPM4j
Can you add this to an `env-var` on the Travis?
We don't want to expose any secrets on our repo.

2019-08-20 14:38 UTC, Abobos commented on .coveralls.yml
> +repo_token: oXbUEfKxrsWp5IKNRE13j9RMBpGnTPM4j
Okay..very cool

2019-08-20 15:00 UTC, chukwuemekachm commented
Can you remove the coveralls file, we no longer need it here.

2019-08-20 15:24 UTC, chukwuemekachm approved these changes
LGTM.

2019-08-20 15:24 UTC, merged

2019-08-20 15:32 UTC, justinefe approved these changes