#167728012 Setup API documentation with Swagger
andela/cyclops-backend pull request #21
Opened 2019-08-19 23:50 UTC by richienabuk

**What does this PR do?**

- Setup API documentation with Swagger using JSDoc

  **How should this be manually tested?**

- Clone repo and run `npm install`
- Visit [localhost:3000/api-docs/](http://localhost:3000/api-docs/) on your browser

  **Any background context you want to provide?**

The barefoot nomad project has both backend and frontend. To enhance working effectively on the frontend, standard documentation is required and swagger is recommended.

  **What are the relevant stories?**

[#167728012](https://www.pivotaltracker.com/n/projects/2381984/stories/167728012)

2019-08-20 06:30 UTC, Abobos commented on src/routes/index.js
> +  app.use(express.urlencoded({ extended: false }));
Well done bro... my confusion is that we have body-parser in our app and we are still using express parser..

2019-08-20 07:27 UTC, richienabuk commented on src/routes/index.js
> +  app.use(express.urlencoded({ extended: false }));
@Abobos Yeah... good point.
That's what I had originally but Awa said we needed body-parser which I confirmed with you.

I prefer express parser.

What's your take?

2019-08-20 07:43 UTC, Abobos commented on src/routes/index.js
> +  app.use(express.urlencoded({ extended: false }));
body-parser. But you can as well ask for other team members take.

2019-08-20 16:31 UTC, Wokoro reviewed
Instead of generating documentations with comments, I think I would be better for it to be generated in dedicated files...

E.g

`Users.yml` or `Users.json`

So it would reduce merge conflict when every one start documenting thier endpoints in `routes/index.js`....

2019-08-20 16:31 UTC, Wokoro commented on src/routes/index.js
> +  }));
I think documentations should be contained in a separate .yml or .json file...

I think it would be more appropriate.

2019-08-20 16:49 UTC, Wokoro commented on src/swaggerdoc.js
> +};
I would suggest swagger configuration be nice to a dedicated swagger config file for clearity...

2019-08-20 16:53 UTC, Wokoro commented on src/swaggerdoc.js
> +  apis: [path.resolve(__dirname, './routes/index.js')],
To accomodate multiple documents holding  documentions.

API directory should be updated instead of pointing to just ` index.js`

2019-08-20 16:57 UTC, richienabuk commented on src/routes/index.js
> +  }));
I went with the comment approach because the PT board story specified generating documentation with JSDoc.

2019-08-20 17:10 UTC, richienabuk commented on src/swaggerdoc.js
> +  apis: [path.resolve(__dirname, './routes/index.js')],
ok. I'll adjust that.

2019-08-20 17:28 UTC, Wokoro commented
According to the folder structure presented to us by our TTL, files for documentation should be placed in `./public/api_docs`

I think you should check that up.

2019-08-21 10:07 UTC, dieudonneAwa commented on swaggerDoc.json
> +}
A newline is needed here

2019-08-21 11:42 UTC, dieudonneAwa approved these changes

2019-08-21 11:44 UTC, Abobos approved these changes

2019-08-21 12:02 UTC, chukwuemekachm requested changes
Good work @richienabuk.
Have a few concerns though.

2019-08-21 12:02 UTC, chukwuemekachm commented on src/index.js
> +app.use('/api/v1', indexRoute, userRoute);
Lets expose the `userRoute` via the index route, this way we just import and use `routes`.

2019-08-21 12:02 UTC, chukwuemekachm commented on src/controllers/UserController.js
> +const UserController = {
The team agreed-on using class-based Controllers, why do we now have a module-like controller here?

2019-08-21 12:05 UTC, richienabuk commented on src/controllers/UserController.js
> +const UserController = {
I was basically setting-up for documentation. we've not implemented a working controller yet.
That'll be refactored with the necessary methods.

2019-08-21 12:07 UTC, chukwuemekachm commented on src/controllers/UserController.js
> +const UserController = {
I'm aware this was for the docs, but let's use a class-based controller as we agreed on.

2019-08-21 12:08 UTC, richienabuk commented on src/index.js
> +app.use('/api/v1', indexRoute, userRoute);
Could you please guide me on that?

I had difficulty using that approach. I worked with @Abobos on that.

2019-08-21 12:11 UTC, chukwuemekachm commented on src/index.js
> +app.use('/api/v1', indexRoute, userRoute);
In the index route register the index route as a middleware.
```js
indexRouter.use('/auth', authRoutes);
```

2019-08-21 12:44 UTC, richienabuk commented on src/controllers/UserController.js
> +const UserController = {
I've done that. Thanks for the observation.

2019-08-21 12:50 UTC, chukwuemekachm approved these changes
LGTM.

2019-08-21 12:51 UTC, merged