#168052207 Create and verify Json Web Token
andela/cyclops-backend pull request #29
Opened 2019-08-23 16:01 UTC by dieudonneAwa

**What does this PR do?**
- Create json web token for user registration

**Description of Task to be completed?**
- Create a file to process tokens
- This file exports a class called ProcessToken that has two helper methods i.e `createToken` and `verifyToken`
- Import this file and destructure out the helper method you want to use
- `createToken` will create token by passing a user object as the payload.
- 'verifyToken` will verify the token 

**How should this be manually tested?**
After cloning the repo,
- run `npm i` to install `jsonwebtoken` dependency.
- import the file whenever you want to use and and destructure the class methods from it
- pass in the user object from which you want to create the token
- possibly store the returned value in a variable called `token`
- you can now use the token 

**Any background context you want to provide?**
- [JSON WEB TOKEN](https://www.npmjs.com/package/jsonwebtoken)

 **What are the relevant stories?**
[#168052207](https://www.pivotaltracker.com/n/projects/2381984/stories/168052207)

**Screenshots (if appropriate)**
- None

**Questions:**
- None

2019-08-25 12:56 UTC, justinefe approved these changes

2019-08-27 06:33 UTC, Abobos approved these changes

2019-08-27 10:21 UTC, Abobos approved these changes

2019-08-27 10:30 UTC, chukwuemekachm requested changes
Nice work @dieudonneAwa.
just a single concern.

2019-08-27 10:30 UTC, chukwuemekachm commented on tests/tokenProcessor.test.js
> +      expect(verifiedToken).to.be.an('object');
This should decode the token you created on line 12 and assert that it contains an email property with the value on line 11.

2019-08-27 10:32 UTC, dieudonneAwa commented on tests/tokenProcessor.test.js
> +      expect(verifiedToken).to.be.an('object');
okay

2019-08-27 10:54 UTC, chukwuemekachm approved these changes
LGTM

2019-08-27 10:54 UTC, merged