#167728019 Build API Endpoint for User sign in with Google and Facebook account
andela/cyclops-backend pull request #33
Opened 2019-08-26 10:42 UTC by richienabuk

**What does this PR do?**
Create an endpoint for login with pre-existing Google and Facebook account

  **Description of Task to be completed?**
### For Google account setup:
- Login at [console.developers.google.com](https://console.developers.google.com)
- Create a _new project_
- Select **API library**
- Enable **Google+ API**
- Create **Credentials**
- Add http://localhost:3000/api/v1/auth/google as your domain
- Copy client ID and client Secret and save in .env file

### For Facebook setup:
- Login at [developers.facebook.com](https://developers.facebook.com)
- Click on **myApps** and select **Create App**
- Choose a name and click **Create app id**
- Click dashboard
- Select Facebook login
- Save and copy credentials and save in .env file

  **How should this be manually tested?**
On your command line, run `npm install` to update dependencies,
Configure .env file for database
Obtain social accounts config as stated above
Run `npm run db:migrate`

## For Google:
- Visit http://localhost:3000/api/v1/auth/google on your browser
- Login and you'll see your details in JSON format

## For Facebook:
- Visit http://localhost:3000/api/v1/auth/facebook on your browser
- Login and you'll see your details in JSON format.

  **Any background context you want to provide?**
The story required Facebook and Google login to the API. I decided to use [Passport](http://www.passportjs.org/packages/passport-google-oauth20/) which makes connecting with the social platforms API seamless.

The user data is being populated in the DB.

  **What are the relevant stories?**
[#167728019](https://www.pivotaltracker.com/n/projects/2381984/stories/167728019#)

  **Screenshots (if appropriate)**
None

  **Questions:**
None

  **Further plan:**
When merged, I will like to add the functionality of enabling an existing email user to update the profile and add Facebook & Google login option as an alternative.

2019-08-26 14:19 UTC, dieudonneAwa commented on src/controllers/UserController.js
> +      //   return sendErrorResponse(res, 409, 'User with that email already exist');
Nice work @richienabuk, but I don't think you should be having commented code here.

2019-08-27 09:06 UTC, Abobos approved these changes

2019-08-27 09:30 UTC, Wokoro approved these changes
LGTM

2019-08-27 10:42 UTC, Abobos approved these changes

2019-08-27 13:27 UTC, dieudonneAwa approved these changes

2019-08-27 17:07 UTC, chukwuemekachm requested changes
Nice work @richienabuk.

2019-08-27 17:07 UTC, chukwuemekachm commented on .env.example
> +GOOGLE_CLIENT_ID=rststv565545v53v636636.apps.googleusercontent.com
Why do we have these `env` vars here?

2019-08-27 17:07 UTC, chukwuemekachm commented on README.md
> +- [Es6+ Javascript](https://www.ecma-international.org/ecma-262/9.0/index.html)
Nice one here. I like the initiative.

2019-08-27 17:07 UTC, chukwuemekachm commented on README.md
> +
You can also add your LF and PO as well.

2019-08-27 17:07 UTC, chukwuemekachm commented on src/controllers/SocialLoginController.js
> +import model from '../models';
Why are you using the models directly?
I thought we agreed to use repositories.

2019-08-27 18:07 UTC, richienabuk commented on src/controllers/UserController.js
> +      //   return sendErrorResponse(res, 409, 'User with that email already exist');
It's not part of my task, I added it to test.
I'll remove it the comment.

Thanks for the observation.

2019-08-27 18:07 UTC, richienabuk commented on .env.example
> +GOOGLE_CLIENT_ID=rststv565545v53v636636.apps.googleusercontent.com
That was a mistake. I'll update that.

2019-08-27 18:10 UTC, richienabuk commented on src/controllers/SocialLoginController.js
> +import model from '../models';
I plan to refactor that in the next PR because somethings I want to implement relies on other PR: user registration, token and log in.
I want to allow for an existing email user to update the account with social login option.

2019-08-27 18:19 UTC, chukwuemekachm commented on src/controllers/SocialLoginController.js
> +import model from '../models';
Do that on this PR.

2019-08-28 10:45 UTC, chukwuemekachm approved these changes
LGTM.

2019-08-28 10:45 UTC, merged