#168244900 Implements user can edit a comment on a trip request
andela/cyclops-backend pull request #47
Opened 2019-09-06 07:55 UTC by Abobos

**What does this PR do?**

Implements user can edit a comment on a trip request

**Description of Task to be completed?**

- Create a PUT route to api/v1/comment/trips/:commentUuid
- Create a  method in comment controller to handle the logic to update a comment

**How should this be manually tested?**

* Open terminal
* Clone this repo
* run ``npm install``
* run ``npm run dev``
* Open Postman
* Goto PUT http://localhost:3000/api/v1/comment/trips/:commentUuid
* Enter your request details like so:

  * message: 'Please approve my request'
  

**Any background context you want to provide?**

None

**What are the relevant stories?**
[#168244900](https://www.pivotaltracker.com/story/show/168244900)

**Screenshots (if appropriate)**

None

**Questions:**

None

2019-09-09 22:01 UTC, Wokoro approved these changes
LGTM.

2019-09-10 11:13 UTC, dieudonneAwa approved these changes

2019-09-10 17:51 UTC, richienabuk approved these changes

2019-09-10 19:23 UTC, justinefe approved these changes

2019-09-10 19:24 UTC, justinefe approved these changes

2019-09-11 14:32 UTC, chukwuemekachm requested changes

2019-09-11 14:32 UTC, chukwuemekachm commented on src/controllers/CommentController.js
> +      // checking if the user is a manager
No need for these comments.

2019-09-11 14:32 UTC, chukwuemekachm commented on src/controllers/TripRequestController.js
> +      // transferring control to controller methode based on request type
Remove this as well.

2019-09-11 21:05 UTC, chukwuemekachm approved these changes
LGTM

2019-09-11 21:05 UTC, merged